apiVersion: v1
data:
  OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT: http://tempo.tempo:14268/api/traces
  OTEL_SERVICE_NAME: innoq-app
  PYROSCOPE_URL: http://pyroscope.pyroscope:4040
kind: ConfigMap
metadata:
  name: innoq-app-gm2md9mtdb
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: innoq-app
spec:
  components:
  - name: innoq-app
    properties:
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            key: OTEL_SERVICE_NAME
            name: innoq-app-gm2md9mtdb
      - name: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
            name: innoq-app-gm2md9mtdb
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            key: PYROSCOPE_URL
            name: innoq-app-gm2md9mtdb
      image: sselzer/innoq-app:7e05d04
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    - properties:
        domain: innoq-app.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    type: webservice
