apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: first-app
  name: first-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - image: sselzer/first-app:13b0b51
        name: app
        ports:
        - containerPort: 8080
