apiVersion: v1
data:
  OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT: http://tempo.observability:14268/api/traces
  OTEL_SERVICE_NAME: order
  PYROSCOPE_URL: http://pyroscope.observability:4040
kind: ConfigMap
metadata:
  name: order-88gchb46m4
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: order
spec:
  components:
  - name: order
    properties:
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            key: OTEL_SERVICE_NAME
            name: order-88gchb46m4
      - name: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
            name: order-88gchb46m4
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            key: PYROSCOPE_URL
            name: order-88gchb46m4
      image: sselzer/order:5b6a0f1
      port: 8080
    traits:
    - properties:
        app.kubernetes.io/name: order
      type: labels
    - properties:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        cpuPercent: 80
        max: 3
        min: 1
      type: cpuscaler
    - properties:
        domain: order.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    type: webservice
