apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test3
spec:
  components:
  - name: test3
    properties:
      image: sselzer/test3:458b354
      port: 8080
    traits:
    - properties:
        domain: test3.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    - type: argocd
    type: webservice
