apiVersion: v1
data:
  OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT: http://tempo.tempo:14268/api/traces
  OTEL_SERVICE_NAME: example-app
  PYROSCOPE_URL: http://pyroscope.pyroscope:4040
kind: ConfigMap
metadata:
  name: example-app-tg5k28ddf2
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: example-app
spec:
  components:
  - name: example-app
    properties:
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            key: OTEL_SERVICE_NAME
            name: example-app-tg5k28ddf2
      - name: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
            name: example-app-tg5k28ddf2
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            key: PYROSCOPE_URL
            name: example-app-tg5k28ddf2
      image: sselzer/example-app:91d4fd9
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        cpuPercent: 80
        max: 3
        min: 1
      type: cpuscaler
    - properties:
        domain: example-app.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    type: webservice
