apiVersion: v1
kind: Service
metadata:
  name: third-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: third-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: third-app
  name: third-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: third-app
  template:
    metadata:
      labels:
        app: third-app
    spec:
      containers:
      - image: sselzer/third-app:b76dce6
        name: app
        ports:
        - containerPort: 8080
