apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-c
spec:
  components:
  - name: app-c
    properties:
      image: sselzer/app-c:5aaa1a3
      port: 8080
    traits:
    - properties:
        domain: app-c.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    - type: argocd
    type: webservice
