apiVersion: v1
kind: Service
metadata:
  name: second-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: second-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: second-app
  name: second-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
      - image: sselzer/second-app:6b18588
        name: app
        ports:
        - containerPort: 8080
