apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: second-app
spec:
  components:
  - name: second-app
    properties:
      image: sselzer/second-app:a539014
      port: 8080
    traits:
    - properties:
        domain: second-app.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    - type: argocd
    type: webservice
