apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-b
spec:
  components:
  - name: app-b
    properties:
      image: sselzer/app-b:bdfbae5
      port: 8080
    traits:
    - properties:
        domain: app-b.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    type: webservice
