apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo.observability:4318/v1/traces
  OTEL_SERVICE_NAME: app-b
  PYROSCOPE_URL: http://pyroscope.observability:4040
kind: ConfigMap
metadata:
  name: app-b-g4mgmc5dct
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-b
spec:
  components:
  - name: app-b
    properties:
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            key: OTEL_SERVICE_NAME
            name: app-b-g4mgmc5dct
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            name: app-b-g4mgmc5dct
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            key: PYROSCOPE_URL
            name: app-b-g4mgmc5dct
      image: sselzer/app-b:7fed9bf
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        domain: app-b.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 3
        min: 1
      type: cpuscaler
    type: webservice
