apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-b
spec:
  components:
  - name: app-b
    properties:
      env:
      - name: username
        valueFrom:
          secretKeyRef:
            key: username
            name: app-b-db
      - name: password
        valueFrom:
          secretKeyRef:
            key: password
            name: app-b-db
      - name: endpoint
        valueFrom:
          secretKeyRef:
            key: endpoint
            name: app-b-db
      - name: port
        valueFrom:
          secretKeyRef:
            key: port
            name: app-b-db
      image: sselzer/app-b:1903e8d
      port: 8080
    traits:
    - properties:
        domain: app-b.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    - type: argocd
    type: webservice
