apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://loki.loki:4318
  OTEL_SERVICE_NAME: app-a
kind: ConfigMap
metadata:
  name: app-a-26mgc56t52
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-a
spec:
  components:
  - name: app-a
    properties:
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            key: OTEL_SERVICE_NAME
            name: app-a-26mgc56t52
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: OTEL_EXPORTER_OTLP_ENDPOINT
            name: app-a-26mgc56t52
      image: sselzer/app-a:c9b5a64
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        domain: app-a.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    type: webservice
