apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-a
spec:
  components:
  - name: app-a
    properties:
      image: sselzer/app-a:5acd31e
      port: 8080
    traits:
    - properties:
        domain: app-a.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    type: webservice
