apiVersion: v1
data:
  OTEL_SERVICE_NAME: app-a
  OTEL_TRACE_ENDPOINT: http://loki.loki:4318/v1/traces
kind: ConfigMap
metadata:
  name: app-a-t8m6mmdh2d
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-a
spec:
  components:
  - name: app-a
    properties:
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            key: OTEL_SERVICE_NAME
            name: app-a-t8m6mmdh2d
      - name: OTEL_TRACE_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: OTEL_TRACE_ENDPOINT
            name: app-a-t8m6mmdh2d
      image: sselzer/app-a:b6c4cae
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        domain: app-a.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    type: webservice
