apiVersion: kro.run/v1alpha1
kind: Application
metadata:
  name: app-a
spec:
  name: app-a
  replicas: 1
  ingress:
    enabled: true
  env:
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo.observability:4318/v1/traces
    OTEL_SERVICE_NAME: app-a
    PYROSCOPE_URL: http://pyroscope.observability:4040
    SERVICE_B_URL: http://app-b.app-b:8080
