apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://tempo.tempo:4318/v1/traces
  OTEL_SERVICE_NAME: app-a
  PYROSCOPE_URL: http://pyroscope.pyroscope:4040
  SERVICE_B_URL: http://app-b.app-b:8080
kind: ConfigMap
metadata:
  name: app-a-d5gb6tt7fk
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-a
spec:
  components:
  - name: app-a
    properties:
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            key: OTEL_SERVICE_NAME
            name: app-a-d5gb6tt7fk
      - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            name: app-a-d5gb6tt7fk
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            key: PYROSCOPE_URL
            name: app-a-d5gb6tt7fk
      - name: SERVICE_B_URL
        valueFrom:
          configMapKeyRef:
            key: SERVICE_B_URL
            name: app-a-d5gb6tt7fk
      image: sselzer/app-a:06d9061
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        domain: app-a.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 3
        min: 1
      type: cpuscaler
    type: webservice
