apiVersion: v1
data:
  OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT: http://tempo.tempo:14268/api/traces
  OTEL_SERVICE_NAME: order
  PYROSCOPE_URL: http://pyroscope.pyroscope:4040
kind: ConfigMap
metadata:
  name: order-k9bm99mh9f
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: order
spec:
  components:
  - name: order
    properties:
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            key: OTEL_SERVICE_NAME
            name: order-k9bm99mh9f
      - name: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
            name: order-k9bm99mh9f
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            key: PYROSCOPE_URL
            name: order-k9bm99mh9f
      image: sselzer/order:5c78a97
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        cpuPercent: 80
        max: 3
        min: 1
      type: cpuscaler
    type: webservice
