apiVersion: v1
data:
  MANAGEMENT_OTLP_TRACING_ENDPOINT: http://tempo.tempo:4318/v1/traces
  PYROSCOPE_URL: http://pyroscope.pyroscope:4040
kind: ConfigMap
metadata:
  name: techdemo-674db5cch8
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: techdemo
spec:
  components:
  - name: techdemo
    properties:
      env:
      - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: MANAGEMENT_OTLP_TRACING_ENDPOINT
            name: techdemo-674db5cch8
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            key: PYROSCOPE_URL
            name: techdemo-674db5cch8
      image: sselzer/techdemo:eb976c1
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        cpuPercent: 80
        max: 3
        min: 1
      type: cpuscaler
    type: webservice
