apiVersion: v1
data:
  MANAGEMENT_OTLP_TRACING_ENDPOINT: http://tempo.tempo:4318/v1/traces
  PYROSCOPE_URL: http://pyroscope.pyroscope:4040
kind: ConfigMap
metadata:
  name: test-app-674db5cch8
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-app
spec:
  components:
  - name: test-app
    properties:
      env:
      - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: MANAGEMENT_OTLP_TRACING_ENDPOINT
            name: test-app-674db5cch8
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            key: PYROSCOPE_URL
            name: test-app-674db5cch8
      image: sselzer/test-app:b8e8961
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        domain: test-app.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 3
        min: 1
      type: cpuscaler
    type: webservice
