apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-app
spec:
  components:
  - name: test-app
    properties:
      image: sselzer/test-app:29cc798
      port: 8080
    traits:
    - properties:
        domain: test-app.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    type: webservice
