apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: test-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: sselzer/test-app:2fec616
        name: app
        ports:
        - containerPort: 8080
