apiVersion: v1
data:
  OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT: http://tempo.tempo:14268/api/traces
  OTEL_SERVICE_NAME: app-k
  PYROSCOPE_URL: http://pyroscope.pyroscope:4040
kind: ConfigMap
metadata:
  name: app-k-fk67k7c5hm
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: app-k
spec:
  components:
  - name: app-k
    properties:
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            key: OTEL_SERVICE_NAME
            name: app-k-fk67k7c5hm
      - name: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
            name: app-k-fk67k7c5hm
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            key: PYROSCOPE_URL
            name: app-k-fk67k7c5hm
      image: sselzer/app-k:4d6ad7d
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    - properties:
        domain: app-k.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    type: webservice
