apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: httpbin
spec:
  components:
  - name: httpbin
    properties:
      image: kennethreitz/httpbin:latest
      port: 80
    traits:
    - properties:
        cpuPercent: 80
        max: 5
        min: 2
      type: cpuscaler
    - properties:
        class: traefik
        classInSpec: true
        domain: httpbin.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    type: webservice
