apiVersion: v1
data:
  OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT: http://tempo.tempo:14268/api/traces
  OTEL_SERVICE_NAME: golang-demo
  PYROSCOPE_URL: http://pyroscope.pyroscope:4040
kind: ConfigMap
metadata:
  name: golang-demo-ccmfh72ft5
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: golang-demo
spec:
  components:
  - name: golang-demo
    properties:
      env:
      - name: OTEL_SERVICE_NAME
        valueFrom:
          configMapKeyRef:
            key: OTEL_SERVICE_NAME
            name: golang-demo-ccmfh72ft5
      - name: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        valueFrom:
          configMapKeyRef:
            key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
            name: golang-demo-ccmfh72ft5
      - name: PYROSCOPE_URL
        valueFrom:
          configMapKeyRef:
            key: PYROSCOPE_URL
            name: golang-demo-ccmfh72ft5
      image: sselzer/golang-demo:a360123
      port: 8080
    traits:
    - properties:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      type: annotations
    - properties:
        cpuPercent: 80
        max: 3
        min: 1
      type: cpuscaler
    - properties:
        domain: golang-demo.127.0.0.1.nip.io
        http:
          /: 8080
      type: gateway
    type: webservice
